s:
	gcc server.c -o server
	sudo ./server

c1:
	gcc client.c -o client
	sudo ./client

c2:
	gcc client.c -o client
	sudo ./client 1

c3:
	gcc client.c -o client
	sudo ./client 2

clean:
	rm -f server client